services:
  probation-offender-search:
    base-url: http://localhost:4020
  prisoner-offender-search:
    base-url: http://localhost:4010
  prison-api:
    base-url: http://localhost:4030
  ndelius:
    base-url: https://localhost:4040
  assess-risks-and-needs:
    base-url: https://localhost:4050
  case-details:
    base-url: https://localhost:4060
  hmpps-auth:
    base-url: http://localhost:9090