services:
  prison-api:
    base-url: https://api-dev.prison.service.justice.gov.uk
    hmpps-auth:
      username: ${CLIENT_ID}
      password: ${CLIENT_SECRET}
  hmpps-auth:
    base-url: https://sign-in-dev.hmpps.service.justice.gov.uk

