---
# Per environment values which override defaults in hmpps-integration-api/values.yaml

generic-service:
  image:
    repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/hmpps-integration-api-admin-team/hmpps-integration-api-production-ecr

  env:
    SPRING_PROFILES_ACTIVE: production
    SENTRY_ENV: production

  namespace_secrets:
    client-credentials:
      CLIENT_ID: "clientId"
      CLIENT_SECRET: "clientSecret"

  ingress:
    host: hmpps-integration-api-production.apps.live.cloud-platform.service.justice.gov.uk
    annotations:
      nginx.ingress.kubernetes.io/auth-tls-secret: "hmpps-integration-api-production/api-gateway-authentication"

  allowlist:
    april: "81.98.147.183/32"
    emile: "79.173.131.202/32"
    ting: "86.16.172.60/32"
    matt: "86.133.179.207/32"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service

